# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(email: 'nicolas.genest@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'nadya.fortier@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'martin.chantal@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'mathieu.houde@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'patrick.thibault@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'david.boutin@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'mathieu.lortie@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'thomas.carrier@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'serge.savoie@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'francis.patry-jessop@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'mathieu.lefrancois@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'david.larochelle@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'nicolas.pineault@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'david.amyot@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'remi.gagnon@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'timothy.wever@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'kiril.kleinerman@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'emmanuela.derilus@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'abdul.akeeb@codebozz.biz',password: 'password',date_created: '20120618')
User.create(email: 'krista.sheely@codeboxx.biz',password: 'password',date_created: '20120618')
User.create(email: 'jonathan.murray@codeboxx.biz',password: 'password',date_created: '20120618')

Employee.create(first_name: 'Nicolas',last_name: 'Genest',title: 'CEO',email: 'nicolas.genest@codeboxx.biz')
Employee.create(first_name: 'Nadya',last_name: 'Fortier',title: 'Director',email: 'nadya.fortier@codeboxx.biz')
Employee.create(first_name: 'Martin',last_name: 'Chantal',title: 'Assistant Director ',email: 'martin.chantal@codeboxx.biz')
Employee.create(first_name: 'Mathieu',last_name: 'Houde',title: 'Captain',email: 'mathieu.houde@codeboxx.biz')
Employee.create(first_name: 'Patrick ',last_name: 'Thibault',title: 'Captain',email: 'patrick.thibault@codeboxx.biz')
Employee.create(first_name: 'David',last_name: 'Boutin',title: 'Engineer',email: 'david.boutin@codeboxx.biz')
Employee.create(first_name: 'Mathieu',last_name: 'Lortie',title: 'Engineer',email: 'mathieu.lortie@codeboxx.biz')
Employee.create(first_name: 'Thomas',last_name: 'Carrier',title: 'Engineer',email: 'thomas.carrier@codeboxx.biz')
Employee.create(first_name: 'Serge',last_name: 'Savoie',title: 'Enigneer',email: 'serge.savoie@codeboxx.biz')
Employee.create(first_name: 'Francis',last_name: 'Patry-Jessop',title: 'Engineer',email: 'francis.patry-jessop@codeboxx.biz')
Employee.create(first_name: 'Mathieu',last_name: 'Lefrancois',title: 'Engineer',email: 'mathieu.lefrancois@codeboxx.biz')
Employee.create(first_name: 'David',last_name: 'Larochelle',title: 'Engineer',email: 'david.larochelle@codeboxx.biz')
Employee.create(first_name: 'Nicolas',last_name: 'Pineault',title: 'Engineer',email: 'nicolas.pineault@codeboxx.biz')
Employee.create(first_name: 'David',last_name: 'Amyot',title: 'Engineer',email: 'david.amyot@codeboxx.biz')
Employee.create(first_name: 'Remi',last_name: 'Gagnon',title: 'Engineer' ,email: 'remi.gagnon@codeboxx.biz')
Employee.create(first_name: 'Timothy',last_name: 'Wever',title: 'Developer',email: 'timothy.wever@codeboxx.biz')
Employee.create(first_name: 'Kiril',last_name: 'Kleinerman',title: 'Developer',email: 'kiril.kleinerman@codeboxx.biz')
Employee.create(first_name: 'Emmanuela',last_name: 'Derilus',title: 'Developer',email: 'emmanuela.derilus@codeboxx.biz')
Employee.create(first_name: 'Abdul',last_name: 'Akeeb',title: 'Developer',email: 'abdul.akeeb@codebozz.biz')
Employee.create(first_name: 'Krista',last_name: 'Sheely',title: 'Developer',email: 'krista.sheely@codeboxx.biz')
Employee.create(first_name: 'Jonathan',last_name: 'Murray',title: 'Developer',email: 'jonathan.murray@codeboxx.biz')